import os
import yagmail
from dotenv import load_dotenv

load_dotenv()

EMAIL_USER=os.getenv("EMAIL_USER")
EMAIL_PASSWORD=os.getenv("EMAIL_PASSWORD")

def send_email(
        recipient,
        incident_id,
        location,
        risk,
        summary,
        attachment=None
):
    
    yag=yagmail.SMTP(
        EMAIL_USER,
        EMAIL_PASSWORD
    )

    subject = f" Her-Shield Emergency Alert | Incident #{incident_id}"
    body = f"""
Dear Officer,

This is an automated emergency notification generated by the Her-Shield Safety Monitoring System.

An incident has been detected and assessed as requiring immediate attention.

------------------------------------------------------------

Incident ID :
{incident_id}

Risk Level :
{risk}

Location :
{location}

Incident Summary :
{summary}

------------------------------------------------------------

A detailed incident report has been attached to this email in PDF format.

Kindly review the attached report and initiate the necessary emergency response procedures at the earliest.

This notification was generated automatically by the Her-Shield AI Emergency Response Platform.

Regards,

Her-Shield Emergency Response System
AI Incident Monitoring Platform

 This is an automatically generated email. Please do not reply.
"""
    
    contents=[body]

    if attachment:
        contents.append(attachment)

    yag.send(
        to=recipient,
        subject=subject,
        contents=contents
    )   

    print("=" * 60)
    print("Emergency email sent successfully")
    print(f"Recipient : {recipient}")
    print(f"Incident  : {incident_id}")
    print("=" * 60)